services:
  db:
    image: postgres:15
    container_name: forum-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: forum-backend
    env_file: ./backend/.env.docker
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: forum-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: